// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcltopgucvimlpncgtmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjbHRvcGd1Y3ZpbWxwbmNndG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjIzOTgsImV4cCI6MjA1OTYzODM5OH0.Ihq7Hce-ONuvl4FzD31JV4lY0XGNt4ZDi_ANH0PbJew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);